site_name: Computational Physics
site_url: https://github.com/Mattia04/WS
theme:
  language: en
  name: material
  font:
    text: Garamond
    code: Fira Code
  highlightjs: true
  features:
    - navigation.footer
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-night
        name: Light mode
    # dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-sunny
        name: Dark mode
extra_css:
  - stylesheets/custom.css
  - https://unpkg.com/katex@0/dist/katex.min.css
extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
extra:
  social:
    - icon: simple/github
      link: https://github.com/Mattia04
  generator: false

copyright: Copyright &copy; 2025 Mattia Ballico

